language: php

php:
  - 5.6
  - 7.0
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - travis_retry composer update --no-interaction

script:
  - vendor/bin/phpcs -p --warning-severity=0 src/ tests/
  - vendor/bin/phpunit --coverage-clover=./tests/report/coverage.clover --testsuite=coverage
  - vendor/bin/phpunit --testsuite=performance

after_script:
  - ./build/coverage_to_scruitinizer.sh
